ADMIN_COMMAND_ORDER = '⚔️Приказы'
ADMIN_COMMAND_STATUS = '🔎Статус'
ADMIN_COMMAND_GROUPS = '👥Группы'
ADMIN_COMMAND_RECRUIT = '📬Заявки'
ADMIN_COMMAND_FIRE_UP = '🔥Чистка'
ADMIN_COMMAND_SQUAD_LIST = '🗂Отряды'
ADMIN_COMMAND_ADMINPANEL = '🌚Я админ'
ADMIN_COMMAND_REPORTS = '📜Репорты'

USER_COMMAND_ME = '🏅Герой'
USER_COMMAND_TOP = '🌟Топ'
USER_COMMAND_SQUAD = '⚜️Отряд'
USER_COMMAND_STATISTICS = '📊Статистика'
USER_COMMAND_BUILD = ''
USER_COMMAND_CONTACTS = '💬Связь'
USER_COMMAND_SQUAD_REQUEST = '⚜️Хочу в отряд'
USER_COMMAND_SQUAD_LEAVE = '☄️Покинуть отряд'

USER_COMMAND_BACK = '🔙Назад'

TOP_COMMAND_ATTACK = '⚔'
TOP_COMMAND_DEFENCE = '🛡'
TOP_COMMAND_EXP = '🔥'
TOP_COMMAND_BUILD = ''

TOP_COMMAND_BATTLES = '⛳️'

STATISTICS_COMMAND_EXP = '🔥Опыт'
